# Generated by Django 6.0.3 on 2026-03-23 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_image', models.ImageField(upload_to='charts/')),
                ('pair', models.CharField(choices=[('EURUSD', 'EUR/USD'), ('GBPUSD', 'GBP/USD'), ('USDJPY', 'USD/JPY'), ('XAUUSD', 'XAU/USD (Gold)'), ('BTCUSD', 'BTC/USD'), ('GBPJPY', 'GBP/JPY'), ('AUDUSD', 'AUD/USD'), ('USDCAD', 'USD/CAD'), ('NAS100', 'NAS100'), ('US30', 'US30'), ('OTHER', 'Other')], default='EURUSD', max_length=10)),
                ('timeframe', models.CharField(choices=[('MN', 'Monthly'), ('W1', 'Weekly'), ('D1', 'Daily'), ('H4', '4 Hour'), ('H1', '1 Hour'), ('M15', '15 Min'), ('M5', '5 Min'), ('M1', '1 Min')], default='H1', max_length=5)),
                ('session', models.CharField(choices=[('ASIAN', 'Asian Session'), ('LONDON', 'London Session'), ('NEWYORK', 'New York Session'), ('LONDON_CLOSE', 'London Close'), ('OVERNIGHT', 'Overnight/No Session')], default='LONDON', max_length=20)),
                ('risk_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('notes', models.TextField(blank=True, help_text='Any context or notes about what you see')),
                ('signal', models.CharField(blank=True, choices=[('TRADE', 'Trade Setup'), ('WAIT', 'Wait & Watch'), ('NO_TRADE', 'No Trade')], max_length=10)),
                ('bias', models.CharField(blank=True, max_length=20)),
                ('market_structure', models.TextField(blank=True)),
                ('key_levels', models.TextField(blank=True)),
                ('entry_price', models.CharField(blank=True, max_length=20)),
                ('stoploss', models.CharField(blank=True, max_length=20)),
                ('tp1', models.CharField(blank=True, max_length=20)),
                ('tp2', models.CharField(blank=True, max_length=20)),
                ('rr_ratio', models.CharField(blank=True, max_length=10)),
                ('full_analysis', models.TextField(blank=True)),
                ('wait_condition', models.TextField(blank=True)),
                ('no_trade_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
