# Generated by Django 6.0.3 on 2026-03-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartanalysis',
            name='ny_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='chartanalysis',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chartanalysis',
            name='pair',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='chartanalysis',
            name='session',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='chartanalysis',
            name='timeframe',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
